//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 3086462d-ecba-4647-8171-df6f9cee360c aws-my-sample-app-android-v0.7";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
        Regions.US_EAST_1;
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:16bfb688-142c-4bf9-b62a-db1f72ac848c";
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "waffletest-contentdelivery-mobilehub-1010075498";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "waffletest-userfiles-mobilehub-1010075498";
}
